name: validate

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.23"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go }}"
          check-latest: true
      - uses: ./.github/actions/check_format
      - uses: ./.github/actions/build
      - uses: ./.github/actions/test
      
  # coverage:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Setup Go
  #       uses: actions/setup-go@v5
  #     - name: Coverage
  #       run: |
  #         go test -v -covermode=count -coverprofile=coverage.cov ./...
  #     # - name: Coveralls
  #     #   uses: coverallsapp/github-action@v2
  #     #   with:
  #     #     file: coverage.cov
  #     #     format: golang